#+TITLE: Tutorial sobre GitHub Pages
#+DESCRIPTION: Tutorial sobre GitHub Pages
#+KEYWORDS: github pages,tutorial
#+LANGUAGE: es
#+AUTHOR: Iván Ruvalcaba
#+EMAIL: ivanruvalcaba@disroot.org
#+EXPORT_FILE_NAME: ./public/index.html
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="https://develop.spacemacs.org/favicon.ico" />
#+HTML_HEAD: <style>#content{max-width:1800px;}</style>
#+HTML_HEAD: <style>p{max-width:800px;}</style>
#+HTML_HEAD: <style>li{max-width:800px;}</style>

* Acerca de Github Pages

/GitHub Pages/ es un servicio de alojamiento de páginas web estáticas que recopila archivos HTML, CSS y JavaScript directamente desde un repositorio albergado en GitHub, opcionalmente procesa estos archivos a través de un proceso de construcción, para posteriormente publicarlos como un sitio web.

Por defecto, Github Pages aloja los sitios web bajo el dominio =github.io=; sin embargo, es posible utilizar su propio dominio personalizado si así lo prefiere.

#+BEGIN_COMMENT
Incluir información sobre cómo [[https://docs.github.com/en/articles/using-a-custom-domain-with-github-pages][utilizar un dominio personalizado con GitHub Pages]].
#+END_COMMENT

* Tipos de sitios en GitHub Pages

Existen tres tipos de sitios web para GitHub Pages: sitios de proyecto, de usuario y de organización. Los sitios de proyecto están conectados a un proyecto específico alojado en [[https://github.com][GitHub]], como una librería JavaScript o una colección de recetas. Los sitios de usuario u organización están conectados a una cuenta específica en GitHub.com.

Sólo es posible crear un sitio de usuario u organización por cada cuenta en GitHub. Los sitios de proyectos, ya sean propiedad de una organización o de una cuenta personal, son ilimitados.

** Páginas de usuario u organización

Para publicar una /página de usuario o de organización/, es necesario crear un repositorio en GitHub llamado =nombredeusuario.github.io= donde =nombredeusuario= es reemplazado por su nombre de usuario en GitHub.

** Páginas de proyecto

Las /páginas de proyecto/ son diferentes a las /páginas de usuario o de organización/ en el sentido de que todos los archivos relacionados con la creación de la página web deben ubicarse en una rama especial llamada rama *gh-pages* (y no en la rama principal *main* / *master* como en el caso de una página de usuario). Cabe destacar que para generar una página de proyecto, no resulta necesaria la creación de esta última, sin embargo, la dirección URL seguirá siendo =nombredeusuario.github.io= aunado al nombre del repositorio que alberga al proyecto, por ejemplo: =miasombrosoproyecto=, quedando en este caso la dirección URL de la siguiente manera: =nombredeusuario.github.io/miasombrosoproyecto=.
