#+TITLE: Cómo publicar de forma automatizada sitios web en GitHub Pages utilizando Emacs y Org-mode
#+DESCRIPTION: Tutorial sobre GitHub Pages
#+KEYWORDS: tutorial,github-pages,emacs,org-mode
#+LANGUAGE: es
#+AUTHOR: Iván Ruvalcaba
#+EMAIL: ivanruvalcaba@disroot.org
#+EXPORT_FILE_NAME: ./public/index.html
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="https://develop.spacemacs.org/favicon.ico" />
#+HTML_HEAD: <style>#content{max-width:1800px;}</style>
#+HTML_HEAD: <style>p{max-width:800px;}</style>
#+HTML_HEAD: <style>li{max-width:800px;}</style>

* Introducción

En el presente tutorial se mostrará el procedimiento a seguir para la publicación en GitHub Pages de documentos creados en [[https://wikiless.org/wiki/Org-mode?lang=es][Org-mode]].

* Flujo de trabajo

El resultado al que se pretende llegar al seguir el procedimiento aquí propuesto será: establecer una configuración de construcción para que su sitio web se publique automáticamente cada vez que se empuje una confirmación a su repositorio.

Esto es posible a través de la utilización de un servicio de «integración continua» como [[https://github.com/features/actions][GitHub Actions]]. Este tipo de servicio le permite ejecutar un script de construcción para su repositorio en una máquina en la nube para que pueda hacer cosas como ejecutar pruebas en el código o, como en este caso, publicar un sitio web.

* Requerimientos

- Contar con una cuenta de usuario en /GitHub.com/.
- Estar familiarizado con el uso desde la línea de comandos de la utilidad =git=, tanto para la creación, manejo y gestión de repositorios.
- Nociones previas en la utilización de /Emacs / Org-mode/.

** Estructura del repositorio local

#+BEGIN_SRC
  .
  ├───.github
  │   └───workflows
  ├───public
  └───scripts
#+END_SRC

* Apéndice

** Acerca de Github Pages

/GitHub Pages/ es un servicio de alojamiento de sitios web estáticos que recaba archivos HTML, CSS y JavaScript directamente desde un repositorio albergado en GitHub, ofreciendo la posibilidad de procesar de forma opcional dichos archivos por medio de la ejecución de un proceso de construcción, para posteriormente publicarlos como un sitio web.

#+BEGIN_QUOTE
*Importante:* Por defecto, Github Pages aloja la totalidad de sus sitios web bajo el nombre de dominio =github.io=; sin embargo, es posible reemplazarlo por un dominio propio si así se desea.
#+END_QUOTE

#+BEGIN_COMMENT
Incluir información sobre cómo [[https://docs.github.com/en/articles/using-a-custom-domain-with-github-pages][utilizar un dominio personalizado con GitHub Pages]].
#+END_COMMENT

#+BEGIN_COMMENT
Incluir información sobre [[https://github.com/features/actions][GitHub Actions]].
#+END_COMMENT
